# Generated by Django 5.0.6 on 2025-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_backend', '0024_delete_teste_ong_requisicaoadotar_log_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubinfo',
            name='on_true',
            field=models.IntegerField(default=1),
        ),
    ]
